export const GET_POPULAR_FILMS_REQUEST: 'GET_POPULAR_FILMS_REQUEST' = 'GET_POPULAR_FILMS_REQUEST';
export const GET_POPULAR_FILMS_SUCCESS: 'GET_POPULAR_FILMS_SUCCESS' = 'GET_POPULAR_FILMS_SUCCESS';
export const GET_POPULAR_FILMS_FAILED: 'GET_POPULAR_FILMS_FAILED' = 'GET_POPULAR_FILMS_FAILED';

export const GET_PREMIERS_REQUEST: 'GET_PREMIERS_REQUEST' = 'GET_PREMIERS_REQUEST';
export const GET_PREMIERS_SUCCESS: 'GET_PREMIERS_SUCCESS' = 'GET_PREMIERS_SUCCESS';
export const GET_PREMIERS_FAILED: 'GET_POPULAR_FILMS_FAILED' = 'GET_POPULAR_FILMS_FAILED';