export const SET__SEARCH: 'SET__SEARCH' = 'SET__SEARCH';
export const RESET__SEARCH: 'RESET__SEARCH' = 'RESET__SEARCH';

export const KEYWORD__SEARCH__REQUEST: 'KEYWORD__SEARCH__REQUEST' = 'KEYWORD__SEARCH__REQUEST';
export const KEYWORD__SEARCH__SUCCESS: 'KEYWORD__SEARCH__SUCCESS' = 'KEYWORD__SEARCH__SUCCESS';
export const KEYWORD__SEARCH__FAILED: 'KEYWORD__SEARCH__FAILED' = 'KEYWORD__SEARCH__FAILED';
