export const SET__MOVIE__ID: 'SET__MOVIE__ID' = 'SET__MOVIE__ID';
export const RESET__MOVIE__ID: 'RESET__MOVIE__ID' = 'RESET__MOVIE__ID';

export const GET_MOVIE_REQUEST: 'GET_MOVIE_REQUEST' = 'GET_MOVIE_REQUEST';
export const GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS' = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAILED: 'GET_MOVIE_FAILED' = 'GET_MOVIE_FAILED';

export const GET_ACTORS_REQUEST: 'GET_ACTORS_REQUEST' = 'GET_ACTORS_REQUEST';
export const GET_ACTORS_SUCCESS: 'GET_ACTORS_SUCCESS' = 'GET_ACTORS_SUCCESS';
export const GET_ACTORS_FAILED: 'GET_ACTORS_FAILED' = 'GET_ACTORS_FAILED';